[package]
name = "eventually"
description = "Crate for using Event Sourcing in Rust applications"
version = "0.5.0"
edition = "2018"
authors = ["Danilo Cianfrone <danilocianfr@gmail.com>"]
license = "MIT"
readme = "../README.md"
repository = "https://github.com/eventually-rs/eventually-rs"

categories = ["rust-patterns", "web-programming", "asynchronous", "data-structures"]
keywords = ["architecture", "ddd", "event-sourcing", "cqrs", "es"]

[features]

[dependencies]
anyhow = "1.0.38"
futures = "0.3.12"
thiserror = "1.0.23"

[dev-dependencies]
tokio = { version = "1.2.0", features = ["rt", "macros"] }
