[workspace]
members = [
    "eventually",
    "eventually-core",
    "eventually-postgres",
    "eventually-redis",
    "eventually-util",
    "eventually-app-example",
    # New eventually crate
    "eventually-new"
]
